[expo-cli] Add a eas:build:init command
expo/expo-cli pull request #2443
Opened 2020-08-10 08:23 UTC by satya164

## Why

We want to add a separate command to configure the project for eas builds without having to actually start a build.

2020-08-10 09:30 UTC, wkozyra95 commented on packages/expo-cli/src/commands/eas-build/init/action.ts
> +  const spinner = ora('Creating minimal eas.json file');
make sure you always succeed or fail on that spinner

2020-08-10 09:34 UTC, wkozyra95 commented on packages/expo-cli/src/commands/eas-build/init/action.ts
> +async function initAction(projectDir: string, options: BuildOptions): Promise<void> {
I'm not 100% sure what is commanderjs behavior where, but from what I remember if you run
`expo eas:init --profile` then this action would be triggered with options set to  `{ profile: true }`

Make sure if I'm correct and handle that case if necessary

2020-08-11 09:14 UTC, dsokal commented on packages/expo-cli/src/commands/eas-build/init/action.ts
> +  ensureGitStatusIsCleanAsync();
```suggestion
  await ensureGitStatusIsCleanAsync();
```

2020-08-26 09:39 UTC, wkozyra95 requested changes

2020-08-26 09:39 UTC, wkozyra95 commented on packages/expo-cli/src/commands/eas-build/build/action.ts
> +      }
```suggestion
      await builder.enureProjectConfiguredAsync();
```
and `enureProjectConfiguredAsync` on android would  contain only
```
     if (!(await this.isProjectConfiguredAsync())) {
        throw new CommandError(
          'Project is not configured. Please run "expo eas:build:init" first to configure the project'
        );
      }
```

I would suggest replacing `configureProjectAsync` -> `enureProjectConfiguredAsync` in the builder interface

configureProjectAsync would be a public method on builders but not the part of the interface

when building you would call `enureProjectConfiguredAsync` methods
when running init you can call directly `configureProjectAsync`

2020-08-26 09:39 UTC, wkozyra95 commented on packages/expo-cli/src/commands/eas-build/init/action.ts
> +
it's not necessary on android, but if we are forcing the user to setup ios credentials we should also setup android part

2020-08-26 09:46 UTC, wkozyra95 commented on packages/expo-cli/src/commands/eas-build/build/action.ts
> +      }
as a side note
we will probably want to remove project configuration and credentials setup from the builder in the future, this interface should be kept as small as posible

2020-08-26 14:57 UTC, wkozyra95 approved these changes

2020-08-27 09:14 UTC, dsokal approved these changes

2020-08-27 09:15 UTC, dsokal commented
Looks good, please update the changelog! :)

2020-08-27 09:50 UTC, wkozyra95 commented
Also, remember to update documentation here https://github.com/expo/expo/tree/master/docs/pages/build

2020-08-27 09:52 UTC, dsokal commented
> Also, remember to update documentation here https://github.com/expo/expo/tree/master/docs/pages/build

Yeah, actually please open a PR to docs before merging this. 
https://github.com/expo/expo-cli/pull/2442 - please update the docs for this feature too

2020-08-27 09:57 UTC, wkozyra95 commented
> > Also, remember to update documentation here https://github.com/expo/expo/tree/master/docs/pages/build
> 
> Yeah, actually please open a PR to docs before merging this.
> #2442 - please update the docs for this feature too

We talked offline with dominik and we think that it's better to merge it earlier, just make sure that docs are ready before expo-cli is published.

2020-08-30 18:38 UTC, merged