[configure-splash-screen] move `@types/color-string` to dependencies
expo/expo-cli pull request #2739
Opened 2020-09-30 14:09 UTC by wkozyra95

# Why

When adding `@expo/config` to `eas-cli` `color-string` types are missing.

2020-09-30 16:36 UTC, bbarthec requested changes
It's wrong IMO ... 😞 
`@types` are dev time only things. The problem might be happening, because the package exposes the types somehow and it shouldn't 🤔

2020-09-30 17:50 UTC, wkozyra95 commented
> It's wrong IMO ... disappointed
> `@types` are dev time only things. The problem might be happening, because the package exposes the types somehow and it shouldn't thinking

I disagree with that as a general statement, but in this case it's just one type so yes it's easier to make sure it's not reexported

btw we have some other packages with `@types` in dependencies

2020-10-01 08:24 UTC, fson approved these changes

2020-10-01 09:16 UTC, bbarthec approved these changes

2020-10-01 09:19 UTC, merged