[docs] add the "target" warning for export
expo/expo-cli pull request #2802
Opened 2020-10-16 19:31 UTC by cruzach

## Why

we warn if you run `expo publish` in a bare project without the `--target` flag. So we should do the same for `expo export` 

to keep things in one place, i moved the `logBareWorkflowWarnings` code from `expo-cli/publish.ts` to `xdl/Project.ts`, since that's where we do the relevant publishing/exporting work. This also prevents us from calling `getConfig` (which is expensive) more times than we need to

Tested in a bare project:
- `expo export` logs warning ✅ 
- `expo publish` logs warning ✅ 
- `expo export --target bare` does not log warning ✅ 
- `expo publish --target bare` does not log warning ✅ 
- remove `expo` from dependencies in package.json, does not log warning ✅ 

Tested in a managed project:
- never logs warning✅

2020-10-19 10:43 UTC, EvanBacon commented on packages/xdl/src/Project.ts
> +export function logBareWorkflowWarnings(pkg: PackageJSONConfig) {
no new code in Project.ts

2020-10-19 10:58 UTC, EvanBacon requested changes
see comment

2020-10-20 16:23 UTC, cruzach commented on packages/xdl/src/Project.ts
> +export function logBareWorkflowWarnings(pkg: PackageJSONConfig) {
ah okay, didn't know that 👍

2021-06-21 22:36 UTC, EvanBacon commented
Is this still relevant now that selecting workflows are deprecated (at least for builds).

2021-06-21 23:11 UTC, closed without merging