[config-plugins] Add hermes support for ios Podfile.properties.json
expo/expo-cli pull request #3796
Opened 2021-08-24 12:06 UTC by Kudo

# Why

add hermes support for ios.

# How

- xdl-schema related pr: https://github.com/expo/universe/pull/8063
- client related pr: https://github.com/expo/expo/pull/14119
- add `podfileProperties` mod and `withPodfileProperties` plugin
- add `withJsEnginePodfileProps` plugin and will read `config.ios.jsEngine`, then `config.jsEngine` and generate `Podfile.properties.json` accordingly.

# Test Plan

```
 PASS   @expo/config-plugins  src/ios/__tests__/JsEngine-test.ts
  jsEngine
    ✓ returns default engine if no engine is provided (2 ms)
    ✓ return the engine if provided
    ✓ return the engine where platform override config has higher priority (1 ms)
    ✓ set the property from shared `jsEngine` config
    ✓ set the property from platform `jsEngine` override config
    ✓ overwrite the property if an old property is existed (1 ms)
```

2021-08-24 22:53 UTC, EvanBacon commented on packages/config-plugins/src/ios/__tests__/JsEngine-test.ts
> +      [`${JS_ENGINE_PROP_KEY}`]: 'hermes',
```suggestion
      [JS_ENGINE_PROP_KEY]: 'hermes',
```
??

2021-08-24 22:58 UTC, EvanBacon commented on packages/config-types/src/ExpoConfig.ts
> +export type JsEngine = 'hermes' | 'jsc';
This file is generated, first you need to add the types to expo/universe (example: https://github.com/expo/universe/pull/7876) then you can run:

```
yarn generate --path ../../../universe/server/www/xdl-schemas/UNVERSIONED-schema.json
```
[reference](https://github.com/expo/expo-cli/blob/master/packages/config-types/README.md#contributing)

2021-08-24 23:00 UTC, EvanBacon requested changes
Looks good so far, should update the integration test in prebuild-config and add a mock file for `Podfile.properties.json`.

2021-08-31 10:47 UTC, merged

2021-09-25 06:16 UTC, zhigang1992 commented
If we are adding Hermes engine, does it make sense to expose use_flipper! behind a flag as well.

Flipper is rather useful when debugging Hermes code.