[expo-cli] install: use recommended versions from remote
expo/expo-cli pull request #4014
Opened 2021-11-17 11:51 UTC by Simek

# Why

Fixes ENG-2445

# How

This PR adds fetch for the `versions` endpoint and uses the data to install the recommended version taken from `relatedPackages` for a used in the project SDK version.

I have also spotted that only length of `nativeModules` and `other` arrays is used for determining the log message content, so I have refactored them to the counters and I have also streamlined the `messages` array creation a bit.

# Test Plan

`yarn test` run in package directory and `yarn lint` run in workspace root did not yield any errors.

Also I have locally aliased the Expo CLI and have tested those changes "live".

# Preview

<img width="551" alt="Screenshot 2021-11-17 at 12 48 46" src="https://user-images.githubusercontent.com/719641/142195351-bc6664e8-c6fe-49f5-8c88-4632a0afff2a.png">

2021-11-18 02:37 UTC, EvanBacon requested changes
maybe this should reuse the existing logic with `expo upgrade`. Regardless, needs tests.

2021-11-18 08:21 UTC, Simek commented
> maybe this should reuse the existing logic with `expo upgrade`.

Refs: 
* https://github.com/expo/expo-cli/blob/master/packages/expo-cli/src/commands/info/upgradeAsync.ts#L186-L223

My first idea was to use the `upgrade` code but of all the logic is not extracted to separate function and the whole logic and checks seems to be too complex for the simple install usage. 

I would rather separate getter and formatter of versions fetch for SDK and refactor the current `upgrade` code, so it will reuse the helpers. I will look at that, but I'm not sure if it would be in this PR. I also will add the requested tests soon.

2021-12-02 06:31 UTC, EvanBacon approved these changes

2021-12-02 06:31 UTC, EvanBacon commented on packages/expo-cli/src/utils/fetchers.ts
> +  if (sdkVersion && sdkVersions[sdkVersion]) {
sdkVersion in sdkVersions

2021-12-02 06:31 UTC, EvanBacon commented on packages/expo-cli/src/utils/fetchers.ts
> +import { Versions } from 'xdl';
Change file name to reflect the only method exported from the file

2021-12-03 18:47 UTC, merged