[interstitial] Capture analytics event when user selects "custom client"
expo/expo-cli pull request #4023
Opened 2021-11-19 15:56 UTC by lukmccall

# Why

Closes ENG-2268.

# How

- Added a listener that triggers every time user selects something on the interstitial page.
- Pipe `platform` value through interstitial page to obtain it in the listener. 

# Test Plan

I couldn't verify if the events are sent, but I replaced them with console logs. Everything seems to work.

2021-11-22 23:04 UTC, esamelson approved these changes

2021-11-23 03:14 UTC, tcdavis commented on packages/expo-cli/src/commands/start/startAsync.ts
> +        UnifiedAnalytics.logEvent('dev client interstitial page', {
This should still use the 'dev client start command' event

2021-11-23 03:15 UTC, tcdavis commented on packages/expo-cli/src/commands/start/startAsync.ts
> +      UnifiedAnalytics.logEvent('dev client interstitial page', {
same here

2021-11-23 03:21 UTC, tcdavis requested changes
Sorry, we should have talked about what the event should be when scoping!

It will be much easier to look at if we use the same 'dev client start command' as we do with the flag. 
If you could add another property flow_used: interstitial | flag here and when calling the flag directly it will let us see as people switch over and track any issues that come up.

2021-12-08 13:14 UTC, merged