Update @expo/next-adapter/babel - useTransformReactJSXExperimental
expo/expo-cli pull request #4516
Opened 2022-08-14 10:35 UTC by criszz77

Rename `useTransformReactJsxExperimental` to `useTransformReactJSXExperimental`

<img width="1239" alt="image" src="https://user-images.githubusercontent.com/55203625/184532670-9821513b-f4b2-436e-96ae-91eee52f2edb.png">

Playing around with React Native and Next.js. This is my babel file:

```javascript 
module.exports = {
  presets: ['babel-preset-expo', '@expo/next-adapter/babel', 'next/babel'],
  plugins: [
    ['@babel/plugin-transform-flow-strip-types'],
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }]
  ]
};
```

2022-08-15 13:06 UTC, kbrandwijk approved these changes

2022-08-15 13:07 UTC, kbrandwijk requested changes
Please also include the updated build output (babel/index.js).

2022-08-16 05:43 UTC, criszz77 commented
I'm sorry, but I just can't figure out what I'm missing here. 🤔

2022-08-29 19:27 UTC, fum4 commented
@kbrandwijk Can you please approve the workflows? I'm not so sure the changes are correct, but hopefully the tests pass 🤞

2022-08-29 20:54 UTC, kbrandwijk commented
> @kbrandwijk Can you please approve the workflows? I'm not so sure the changes are correct, but hopefully the tests pass 🤞

Like I've asked before, you need to include the updated build output. Run `yarn build` locally which will update the compiled files in the babel folder, and commit those. Thank you!

2022-10-28 07:45 UTC, EvanBacon commented
Closing in favor of #4580

2022-10-28 07:45 UTC, closed without merging